
spring:
  cloud:
    #    nacos:
    #      server-addr: 47.105.155.211:8848
    stream:
      bindings:
        input: {destination: test-topic,content-type: application/json,group: test-group}

      rocketmq:
        binder:
          name-server: 47.105.155.211:9876
  application:
    name: rocketmq-consumer
server:
  port: 8011

