server:
  port: 8011
spring:
  application:
    name: seata-account-demo
  cloud:
    nacos:
      server-addr: 47.105.155.211:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.105.155.211:3306/seata?useSSL=false&serverTimezone=UTC
    username: admin
    password: 123456Liu@
    druid:
      max-active: 20
      min-idle: 2
      initial-size: 2
seata:
  registry:
    type: nacos
    nacos:
      cluster: default
      server-addr: 47.105.155.211:8848
#  config:
#    type: nacos
#    nacos:
#      server-addr: 47.105.155.211:8848


#  spring.datasource.name="accountDataSource"
#  spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
#  spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#  spring.datasource.url=jdbc:mysql://47.105.155.211:3306/seata?useSSL=false&serverTimezone=UTC
#  spring.datasource.username=admin
#  spring.datasource.password=123456Liu@
#  spring.datasource.druid.max-active=20
#  spring.datasource.druid.min-idle=2
#  spring.datasource.druid.initial-size=2

## if use registry center
#seata.registry.type=nacos
#seata.registry.nacos.cluster=default
#seata.registry.nacos.server-addr=localhost

## if use config center
#seata.config.type=apollo
#seata.config.apollo.apollo-meta=http://192.168.1.204:8801
#seata.config.apollo.app-id=seata-server