
spring:
  cloud:
#    nacos:
#      server-addr: 47.105.155.211:8848
    stream:
      bindings:
        output: {destination: test-topic,content-type: application/json}
      rocketmq:
        binder:
          name-server: 47.105.155.211:9876
  application:
    name: rocketmq-producer
server:
  port: 8010
